"""empty message

Revision ID: 54ba8162546d
Revises: 
Create Date: 2023-04-12 22:26:06.465889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ba8162546d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('val_curs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alter_id', sa.String(), nullable=True),
    sa.Column('char_code', sa.String(), nullable=True),
    sa.Column('num_code', sa.Integer(), nullable=True),
    sa.Column('nominal', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.DECIMAL(), nullable=True),
    sa.Column('val_curs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['val_curs_id'], ['val_curs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valute')
    op.drop_table('val_curs')
    # ### end Alembic commands ###
