"""empty message

Revision ID: f1262bc0f6e8
Revises: f21759de45a4
Create Date: 2023-04-13 03:16:08.798295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1262bc0f6e8'
down_revision = 'f21759de45a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_val_curs_request_date'), 'val_curs', ['request_date'], unique=False)
    op.create_index(op.f('ix_valute_char_code'), 'valute', ['char_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valute_char_code'), table_name='valute')
    op.drop_index(op.f('ix_val_curs_request_date'), table_name='val_curs')
    # ### end Alembic commands ###
