"""empty message

Revision ID: f21759de45a4
Revises: 54ba8162546d
Create Date: 2023-04-13 01:52:22.214945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21759de45a4'
down_revision = '54ba8162546d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('val_curs', sa.Column('request_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('val_curs', 'request_date')
    # ### end Alembic commands ###
